Repository thojkooi/terraform-digitalocean-docker-swarm-mode, pull requests merged in 2018-10, with the labels that each got.

#30 fix error user_data must not be empty #29
  README.md
  examples/firewall/main.tf
  examples/manager/add-workers/README.md
  examples/manager/add-workers/main.tf
  examples/manager/remote-api-tls/README.md
  examples/manager/remote-api-tls/main.tf
  examples/manager/user-data/README.md
  examples/manager/user-data/main.tf
  examples/manager/user-data/scripts/install-docker-ce.sh
  examples/multi-role/README.md
  examples/multi-role/main.tf
  modules/managers/main.tf
  modules/managers/scripts/provision-first-manager.sh
  modules/managers/scripts/provision-manager.sh
  modules/managers/variables.tf
  modules/workers/scripts/join.sh
  modules/workers/variables.tf
  variables.tf
Labels: bug-fix, enhancement

#28 Leave a swarm if re-provisioning
  modules/managers/scripts/provision-manager.sh
Labels: enhancement

#31 fix(managers): uncomment user_data variable
  modules/managers/main.tf
Labels: bug-fix
